import { ReactNode } from "react";
import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";

import "./globals.css";

const ubuntu = Ubuntu({
    weight: ["300", "400", "500", "700"],
    style: ["normal", "italic"],
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "Recipedia",
    description: "Generated by create next app",
    icons: [
        {
            url: "/favicon.ico",
            href: "/favicon.ico"
        }
    ]
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en">
            <body className={ubuntu.className}>
                {children}
            </body>
        </html>
    );
};
